[build]
  publish = "dist"
  command = "npm install --include=dev && npm run build"

[build.environment]
  NODE_ENV = "development"
  NPM_FLAGS = "--include=dev"
  NODE_VERSION = "22"
  PYTHON_VERSION = "3.11"
